name = "hostap"
language = "c++"
homepage = "https://w1.fi/cvs.html"
main_repo = "git://w1.fi/srv/git/hostap.git"
repo_to_patch = "hostap"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:8eda74a11e800aead5a041ee479a65b33dab3150d6e89e5694e2b6eb27be98fc"
immutable_files = ["tests/"]
