name = "hdf5"
language = "c"
homepage = "https://www.hdfgroup.org/solutions/hdf5/"
main_repo = "https://github.com/HDFGroup/hdf5"
repo_to_patch = "hdf5"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = ["test"]
