name = "gpac"
language = "c"
homepage = "https://gpac.io"
main_repo = "https://github.com/gpac/gpac"
repo_to_patch = "gpac"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = ["testsuite"]
