name = "libspng"
language = "c++"
homepage = "https://libspng.org"
main_repo = "https://gitlab.com/randy408/libspng.git"
repo_to_patch = "libspng"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:8eda74a11e800aead5a041ee479a65b33dab3150d6e89e5694e2b6eb27be98fc"
immutable_files = ["tests/"]
