name = "bind9"
language = "c"
homepage = "https://gitlab.isc.org/isc-projects/bind9"
main_repo = "https://gitlab.isc.org/isc-projects/bind9.git"
repo_to_patch = "bind9"
build_image = "n132/arvo:63186-fix"
immutable_files = ["tests", "fuzz"]
