name = "wasm3"
language = "c"
homepage = "https://github.com/wasm3/wasm3"
main_repo = "https://github.com/wasm3/wasm3"
repo_to_patch = "wasm3"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:8eda74a11e800aead5a041ee479a65b33dab3150d6e89e5694e2b6eb27be98fc"
immutable_files = ["test"]
