name = "lldpd"
language = "c"
homepage = "https://lldpd.github.io"
main_repo = "https://github.com/lldpd/lldpd/"
repo_to_patch = "lldpd"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:8eda74a11e800aead5a041ee479a65b33dab3150d6e89e5694e2b6eb27be98fc"
immutable_files = ["tests"]
