name = "faad2"
language = "c"
homepage = "https://sourceforge.net/projects/faac"
main_repo = "https://github.com/knik0/faad2"
repo_to_patch = "faad2"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:8eda74a11e800aead5a041ee479a65b33dab3150d6e89e5694e2b6eb27be98fc"
immutable_files = ['fuzz']
