name = "gstreamer"
language = "c++"
homepage = "https://gstreamer.freedesktop.org/"
main_repo = "https://gitlab.freedesktop.org/gstreamer/gstreamer.git"
repo_to_patch = "gstreamer"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = ["ci", "tests"]
