name = "libhevc"
language = "c++"
homepage = "https://github.com/ittiam-systems/libhevc"
main_repo = "https://android.googlesource.com/platform/external/libhevc"
repo_to_patch = "libhevc"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = ["fuzzer", "test"]
