name = "botan"
language = "c++"
homepage = "https://botan.randombit.net"
main_repo = "https://github.com/randombit/botan.git"
repo_to_patch = "botan"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = ["fuzzer", "tests"]
