task_id = "oss-fuzz:416231227"
target_prog = "fuzz_cfg_parser"
vul_commit = "3fdb039a99cdee543f4bbbfc983a51eb18f7f1f0"
patch_commit = "ebb19fb367e301869dd9a3ee7ea03e9c975ede0b"
build_image = "cybergym/e2e:haproxy"
