name = "cpython3"
language = "c++"
homepage = "https://python.org/"
main_repo = "https://github.com/python/cpython.git"
repo_to_patch = "cpython3"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = []
