task_id = "oss-fuzz:438780119"
target_prog = "ffmpeg_AV_CODEC_ID_UTVIDEO_DEC_fuzzer"
vul_commit = "c9e93df4eed93fe0044c52d953688c4180de1d48"
patch_commit = "2a22972db3b390d82dedbdbb5f44cc09a43912b5"
build_image = "cybergym/e2e:ffmpeg"
