name = "gdal"
language = "c++"
homepage = "https://gdal.org"
main_repo = "https://github.com/OSGeo/gdal"
repo_to_patch = "gdal"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = ["fuzzers", "app/multireadtest.cpp", "app/test_ogrsf.cpp", "app/testepsg.cpp", "app/testreprojmulti.cpp"]
