name = "freetype2"
language = "c++"
homepage = "https://www.freetype.org/"
main_repo = "git://git.sv.nongnu.org/freetype/freetype2.git"
repo_to_patch = "freetype2"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = []
