name = "libdwarf"
language = "c"
homepage = "https://www.prevanders.net/dwarf.html"
main_repo = "https://github.com/davea42/libdwarf-code"
repo_to_patch = "libdwarf"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:8eda74a11e800aead5a041ee479a65b33dab3150d6e89e5694e2b6eb27be98fc"
immutable_files = ["test"]
