name = "libgit2"
language = "c++"
homepage = "https://libgit2.github.com/"
main_repo = "https://github.com/libgit2/libgit2"
repo_to_patch = "libgit2"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = []
