name = "libidn2"
language = "c"
homepage = "https://gitlab.com/libidn/libidn2"
main_repo = "https://gitlab.com/libidn/libidn2.git"
repo_to_patch = "libidn2"
immutable_files = ["tests/", "fuzz/"]
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:8eda74a11e800aead5a041ee479a65b33dab3150d6e89e5694e2b6eb27be98fc"