name = "glib"
language = "c++"
homepage = "https://gitlab.gnome.org/GNOME/glib/"
main_repo = "https://gitlab.gnome.org/GNOME/glib"
repo_to_patch = "glib"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = ["fuzzing", "tests"]
