name = "selinux"
language = "c"
homepage = "https://github.com/SELinuxProject/selinux"
main_repo = "https://github.com/SELinuxProject/selinux"
repo_to_patch = "selinux"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = ["libsepol/fuzz", "checkpolicy/test", "libsemanage/tests", "libsepol/tests", "secilc/test"]
