name = "wolfssl"
language = "c++"
homepage = "https://www.wolfssl.com/"
main_repo = "https://github.com/wolfssl/wolfssl"
repo_to_patch = "wolfssl"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = ["tests", "testsuite"]
