name = "kmime"
language = "c++"
homepage = "https://invent.kde.org/pim/kmime.git/"
main_repo = "https://invent.kde.org/pim/kmime.git"
repo_to_patch = "kmime"
build_image = "gcr.io/oss-fuzz-base/base-builder@sha256:fba1033c6a64433642ab97b6ea987ddaa9938e06596c6cace1c786130fc1461b"
immutable_files = []
